--> 'COM_LIST_DS' : table
--> 'OBJID'       : field
SELECT
	c.COLUMN_ID,
	NVL(k.IS_KEY, 'N') IS_KEY,
	c.NULLABLE IS_NULL,
	NVL(k.IS_PUBLIC, 'Y') IS_PUBLIC,
	c.COLUMN_NAME FIELD_NAME,
	c.DATA_TYPE,
	c.DATA_LENGTH,
	c.DATA_DEFAULT
FROM
	USER_TAB_COLUMNS c, (
		SELECT
			ic.COLUMN_NAME,
			'Y' IS_KEY,
			'N' IS_PUBLIC
		FROM
			USER_INDEXES i,
			USER_IND_COLUMNS ic
		WHERE
			UPPER(i.TABLE_NAME) = UPPER('COM_LIST_DS')
			AND i.UNIQUENESS = 'UNIQUE'
			AND i.INDEX_NAME = ic.INDEX_NAME
			AND i.INDEX_NAME LIKE '%PK'
	) k
WHERE
	UPPER(c.TABLE_NAME) = UPPER('COM_LIST_DS')
	AND c.COLUMN_NAME = k.COLUMN_NAME(+)
	--> if(field != null){
	AND UPPER(c.COLUMN_NAME) = UPPER('OBJID')
	--> }
